/*
 * Rekki.com Supplier API
 *
 * The base URL for all API endpoints is https://api.rekki.com  Api key value contains of word Bearer together with api key that you can get from integrations@rekki.com 
 *
 * API version: 
 * Contact: integrations@rekki.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// V3GenericErrorResponse struct for V3GenericErrorResponse
type V3GenericErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// NewV3GenericErrorResponse instantiates a new V3GenericErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV3GenericErrorResponse() *V3GenericErrorResponse {
	this := V3GenericErrorResponse{}
	return &this
}

// NewV3GenericErrorResponseWithDefaults instantiates a new V3GenericErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV3GenericErrorResponseWithDefaults() *V3GenericErrorResponse {
	this := V3GenericErrorResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *V3GenericErrorResponse) GetError() string {
	if o == nil || o.Error == nil {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3GenericErrorResponse) GetErrorOk() (*string, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *V3GenericErrorResponse) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *V3GenericErrorResponse) SetError(v string) {
	o.Error = &v
}

func (o V3GenericErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableV3GenericErrorResponse struct {
	value *V3GenericErrorResponse
	isSet bool
}

func (v NullableV3GenericErrorResponse) Get() *V3GenericErrorResponse {
	return v.value
}

func (v *NullableV3GenericErrorResponse) Set(val *V3GenericErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV3GenericErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV3GenericErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV3GenericErrorResponse(val *V3GenericErrorResponse) *NullableV3GenericErrorResponse {
	return &NullableV3GenericErrorResponse{value: val, isSet: true}
}

func (v NullableV3GenericErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV3GenericErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


