/*
 * Rekki.com Supply API
 *
 * The base URL for all API endpoints is https://api.rekki.com  Api key value contains of word Bearer together with api key that you can get from integrations@rekki.com 
 *
 * API version: 
 * Contact: integrations@rekki.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client
// V3OrderListInput struct for V3OrderListInput
type V3OrderListInput struct {
	// Filters orders created at or after the given unix timestamp (in seconds)
	Since string `json:"since,omitempty"`
	// Only fetch orders that were not marked as integrated
	SkipIntegrated bool `json:"skip_integrated,omitempty"`
}
