/*
 * Rekki.com Supply API
 *
 * The base URL for all API endpoints is https://api.rekki.com  Api key value contains of word Bearer together with api key that you can get from integrations@rekki.com 
 *
 * API version: 
 * Contact: integrations@rekki.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client
// MainSetErrorOrderInput struct for MainSetErrorOrderInput
type MainSetErrorOrderInput struct {
	// Number of attempts made to push the integration
	Attempts int32 `json:"attempts,omitempty"`
	// error message
	Error string `json:"error,omitempty"`
	Order IntegrationOrder `json:"order,omitempty"`
}
