/*
 * Rekki.com Supply API
 *
 * The base URL for all API endpoints is https://api.rekki.com  Api key value contains of word Bearer together with api key that you can get from integrations@rekki.com 
 *
 * API version: 
 * Contact: integrations@rekki.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client
// V3AvailabilityError struct for V3AvailabilityError
type V3AvailabilityError struct {
	Error string `json:"error,omitempty"`
	Item V3StockItemState `json:"item,omitempty"`
}
