/*
 * Rekki.com Supply API
 *
 * The base URL for all API endpoints is https://api.rekki.com  Api key value contains of word Bearer together with api key that you can get from integrations@rekki.com 
 *
 * API version: 
 * Contact: integrations@rekki.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client
// V3DeliveryAddress struct for V3DeliveryAddress
type V3DeliveryAddress struct {
	Address string `json:"address,omitempty"`
	City string `json:"city,omitempty"`
	Country string `json:"country,omitempty"`
	Postcode string `json:"postcode,omitempty"`
}
