/*
 * Rekki.com Supplier API
 *
 * The base URL for all API endpoints is https://api.rekki.com  Api key value contains of word Bearer together with api key that you can get from integrations@rekki.com 
 *
 * API version: 
 * Contact: integrations@rekki.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// MainReplaceCatalogInput struct for MainReplaceCatalogInput
type MainReplaceCatalogInput struct {
	// items to insert
	Data *[]MainAPISupplierCatalogItem `json:"data,omitempty"`
}

// NewMainReplaceCatalogInput instantiates a new MainReplaceCatalogInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMainReplaceCatalogInput() *MainReplaceCatalogInput {
	this := MainReplaceCatalogInput{}
	return &this
}

// NewMainReplaceCatalogInputWithDefaults instantiates a new MainReplaceCatalogInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMainReplaceCatalogInputWithDefaults() *MainReplaceCatalogInput {
	this := MainReplaceCatalogInput{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *MainReplaceCatalogInput) GetData() []MainAPISupplierCatalogItem {
	if o == nil || o.Data == nil {
		var ret []MainAPISupplierCatalogItem
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainReplaceCatalogInput) GetDataOk() (*[]MainAPISupplierCatalogItem, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *MainReplaceCatalogInput) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []MainAPISupplierCatalogItem and assigns it to the Data field.
func (o *MainReplaceCatalogInput) SetData(v []MainAPISupplierCatalogItem) {
	o.Data = &v
}

func (o MainReplaceCatalogInput) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableMainReplaceCatalogInput struct {
	value *MainReplaceCatalogInput
	isSet bool
}

func (v NullableMainReplaceCatalogInput) Get() *MainReplaceCatalogInput {
	return v.value
}

func (v *NullableMainReplaceCatalogInput) Set(val *MainReplaceCatalogInput) {
	v.value = val
	v.isSet = true
}

func (v NullableMainReplaceCatalogInput) IsSet() bool {
	return v.isSet
}

func (v *NullableMainReplaceCatalogInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMainReplaceCatalogInput(val *MainReplaceCatalogInput) *NullableMainReplaceCatalogInput {
	return &NullableMainReplaceCatalogInput{value: val, isSet: true}
}

func (v NullableMainReplaceCatalogInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMainReplaceCatalogInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


