/*
 * Rekki.com Supply API
 *
 * The base URL for all API endpoints is https://api.rekki.com  Api key value contains of word Bearer together with api key that you can get from integrations@rekki.com 
 *
 * API version: 
 * Contact: integrations@rekki.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client
// V3ApiSupplierCatalogUnit struct for V3ApiSupplierCatalogUnit
type V3ApiSupplierCatalogUnit struct {
	// The order price in cents for the item per unit. For example, a currency of GBP with unit 5L and price 850 means a 5L item can be ordered for £8.50.
	PriceCents int32 `json:"price_cents,omitempty"`
	// The number of items in stock for the related unit.
	StockCount int32 `json:"stock_count,omitempty"`
	// A unit that the item can be ordered in.
	Unit string `json:"unit,omitempty"`
}
