/*
 * Rekki.com Supply API
 *
 * The base URL for all API endpoints is https://api.rekki.com  Api key value contains of word Bearer together with api key that you can get from integrations@rekki.com 
 *
 * API version: 
 * Contact: integrations@rekki.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client
// V3Allergens struct for V3Allergens
type V3Allergens struct {
	// List of symptoms for the allergy.
	Symptoms []string `json:"symptoms,omitempty"`
	// Type of allergy. For example \"contains peanuts\" or \"may contain peanuts\".
	Type string `json:"type,omitempty"`
}
