/*
 * Rekki.com Supply API
 *
 * The base URL for all API endpoints is https://api.rekki.com  Api key value contains of word Bearer together with api key that you can get from integrations@rekki.com 
 *
 * API version: 
 * Contact: integrations@rekki.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client
// IntegrationOrder struct for IntegrationOrder
type IntegrationOrder struct {
	// the time at which the supplier confirmed the order (via email, or via the REKKI supplier app, or via the REKKI API)
	ConfirmedAt string `json:"confirmed_at,omitempty"`
	// the phone number or email address for the person who placed the order
	ContactInfo string `json:"contact_info,omitempty"`
	// the full name of the person who placed the order
	ContactName string `json:"contact_name,omitempty"`
	// the account number for customer within the supplier system, this can be setup in REKKI supplier app ( https://supplier.rekki.com ).
	CustomerAccountNo string `json:"customer_account_no,omitempty"`
	// delivery address for this specific order (address, postcode)
	DeliveryAddress string `json:"delivery_address,omitempty"`
	// expected delivery date (when users place orders they specify for which day it is supposed to be delivered)
	DeliveryOn string `json:"delivery_on,omitempty"`
	// when was the order created by the customer (ISO date time)
	InsertedAt string `json:"inserted_at,omitempty"`
	// when was the order created by the customer (unix timestamp in seconds)
	InsertedAtTs int32 `json:"inserted_at_ts,omitempty"`
	// items requests in this order
	Items []IntegrationOrderItem `json:"items,omitempty"`
	// the name of the location that placed the order, can be NULL
	LocationName string `json:"location_name,omitempty"`
	// defined by the user at the moment of making an order and usually refer to that specific order (e.g. \"please send fresher tomatoes\")
	Notes string `json:"notes,omitempty"`
	// REKKI's order reference
	Reference string `json:"reference,omitempty"`
	// notes define by the user for the supplier, usually being common across orders (e.g.: \"please use the side entrance for delivery\")
	SupplierNotes string `json:"supplier_notes,omitempty"`
}
