/*
 * Rekki.com Supply API
 *
 * The base URL for all API endpoints is https://api.rekki.com  Api key value contains of word Bearer together with api key that you can get from integrations@rekki.com 
 *
 * API version: 
 * Contact: integrations@rekki.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client
// V3ApiSupplierCatalogItem struct for V3ApiSupplierCatalogItem
type V3ApiSupplierCatalogItem struct {
	// List of allergens for the item, if any.
	Allergens []V3Allergens `json:"allergens,omitempty"`
	// Availability status of the item. Defaults to in_stock.
	Availability string `json:"availability,omitempty"`
	// Currency code for the price. In ISO 4217 three-letter format. Defaults to GBP.
	Currency string `json:"currency,omitempty"`
	// Product description
	Description string `json:"description,omitempty"`
	// REKKI's ID to uniquely identify the catalog item (for REKKI internal reference).
	Id int32 `json:"id,omitempty"`
	// Item name as would be defined on the customer's product list.
	Name string `json:"name,omitempty"`
	OrderCutoffTimes V3OrderCutoffTimes `json:"order_cutoff_times,omitempty"`
	// Product code for the item that maps to the supplier's catalog. Suppliers can modify the product code for future orders at https://supplier.rekki.com
	ProductCode string `json:"product_code,omitempty"`
	// List of product codes for alternative items when this item is not available.
	ReplacementProducts []string `json:"replacement_products,omitempty"`
	// List of date ranges when the item is in-season.
	Seasonality []V3Seasonality `json:"seasonality,omitempty"`
	// List of units and their prices that the item can be ordered in.
	UnitsPrices []V3ApiSupplierCatalogUnit `json:"units_prices,omitempty"`
}
