/*
 * Rekki.com Supply API
 *
 * The base URL for all API endpoints is https://api.rekki.com  Api key value contains of word Bearer together with api key that you can get from integrations@rekki.com 
 *
 * API version: 
 * Contact: integrations@rekki.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client
// IntegrationOrderItem struct for IntegrationOrderItem
type IntegrationOrderItem struct {
	// REKKI's item id, for REKKI internal reference
	Id string `json:"id,omitempty"`
	// item name as defined on the customer product list
	Name string `json:"name,omitempty"`
	// the item price as set in REKKI
	Price string `json:"price,omitempty"`
	// the item price as set in REKKI, in cents
	PriceCents int32 `json:"price_cents,omitempty"`
	// product code that maps to the supplier catalog, suppliers can modify the product code for the future orders for this customer at https://supplier.rekki.com
	ProductCode string `json:"product_code,omitempty"`
	// quantity
	Quantity float32 `json:"quantity,omitempty"`
	// details/notes provided by the supplier for the item
	Spec string `json:"spec,omitempty"`
	// item unit as defined on the customer product list
	Units string `json:"units,omitempty"`
}
