/*
 * Rekki.com Supplier API
 *
 * The base URL for all API endpoints is https://api.rekki.com  Api key value contains of word Bearer together with api key that you can get from integrations@rekki.com 
 *
 * API version: 
 * Contact: integrations@rekki.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// MainSetIntegrateOrdersInput struct for MainSetIntegrateOrdersInput
type MainSetIntegrateOrdersInput struct {
	// Array of References of the orders to confirm, required. Order refs are discoverable when listing orders.
	Orders *[]map[string]interface{} `json:"orders,omitempty"`
}

// NewMainSetIntegrateOrdersInput instantiates a new MainSetIntegrateOrdersInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMainSetIntegrateOrdersInput() *MainSetIntegrateOrdersInput {
	this := MainSetIntegrateOrdersInput{}
	return &this
}

// NewMainSetIntegrateOrdersInputWithDefaults instantiates a new MainSetIntegrateOrdersInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMainSetIntegrateOrdersInputWithDefaults() *MainSetIntegrateOrdersInput {
	this := MainSetIntegrateOrdersInput{}
	return &this
}

// GetOrders returns the Orders field value if set, zero value otherwise.
func (o *MainSetIntegrateOrdersInput) GetOrders() []map[string]interface{} {
	if o == nil || o.Orders == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Orders
}

// GetOrdersOk returns a tuple with the Orders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainSetIntegrateOrdersInput) GetOrdersOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Orders == nil {
		return nil, false
	}
	return o.Orders, true
}

// HasOrders returns a boolean if a field has been set.
func (o *MainSetIntegrateOrdersInput) HasOrders() bool {
	if o != nil && o.Orders != nil {
		return true
	}

	return false
}

// SetOrders gets a reference to the given []map[string]interface{} and assigns it to the Orders field.
func (o *MainSetIntegrateOrdersInput) SetOrders(v []map[string]interface{}) {
	o.Orders = &v
}

func (o MainSetIntegrateOrdersInput) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Orders != nil {
		toSerialize["orders"] = o.Orders
	}
	return json.Marshal(toSerialize)
}

type NullableMainSetIntegrateOrdersInput struct {
	value *MainSetIntegrateOrdersInput
	isSet bool
}

func (v NullableMainSetIntegrateOrdersInput) Get() *MainSetIntegrateOrdersInput {
	return v.value
}

func (v *NullableMainSetIntegrateOrdersInput) Set(val *MainSetIntegrateOrdersInput) {
	v.value = val
	v.isSet = true
}

func (v NullableMainSetIntegrateOrdersInput) IsSet() bool {
	return v.isSet
}

func (v *NullableMainSetIntegrateOrdersInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMainSetIntegrateOrdersInput(val *MainSetIntegrateOrdersInput) *NullableMainSetIntegrateOrdersInput {
	return &NullableMainSetIntegrateOrdersInput{value: val, isSet: true}
}

func (v NullableMainSetIntegrateOrdersInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMainSetIntegrateOrdersInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


