/*
 * Rekki.com Supplier API
 *
 * The base URL for all API endpoints is https://api.rekki.com  Api key value contains of word Bearer together with api key that you can get from integrations@rekki.com 
 *
 * API version: 
 * Contact: integrations@rekki.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// V3SuccessConfirmation struct for V3SuccessConfirmation
type V3SuccessConfirmation struct {
	Success *bool `json:"success,omitempty"`
}

// NewV3SuccessConfirmation instantiates a new V3SuccessConfirmation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV3SuccessConfirmation() *V3SuccessConfirmation {
	this := V3SuccessConfirmation{}
	return &this
}

// NewV3SuccessConfirmationWithDefaults instantiates a new V3SuccessConfirmation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV3SuccessConfirmationWithDefaults() *V3SuccessConfirmation {
	this := V3SuccessConfirmation{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *V3SuccessConfirmation) GetSuccess() bool {
	if o == nil || o.Success == nil {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3SuccessConfirmation) GetSuccessOk() (*bool, bool) {
	if o == nil || o.Success == nil {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *V3SuccessConfirmation) HasSuccess() bool {
	if o != nil && o.Success != nil {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *V3SuccessConfirmation) SetSuccess(v bool) {
	o.Success = &v
}

func (o V3SuccessConfirmation) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Success != nil {
		toSerialize["success"] = o.Success
	}
	return json.Marshal(toSerialize)
}

type NullableV3SuccessConfirmation struct {
	value *V3SuccessConfirmation
	isSet bool
}

func (v NullableV3SuccessConfirmation) Get() *V3SuccessConfirmation {
	return v.value
}

func (v *NullableV3SuccessConfirmation) Set(val *V3SuccessConfirmation) {
	v.value = val
	v.isSet = true
}

func (v NullableV3SuccessConfirmation) IsSet() bool {
	return v.isSet
}

func (v *NullableV3SuccessConfirmation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV3SuccessConfirmation(val *V3SuccessConfirmation) *NullableV3SuccessConfirmation {
	return &NullableV3SuccessConfirmation{value: val, isSet: true}
}

func (v NullableV3SuccessConfirmation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV3SuccessConfirmation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


