/*
 * Rekki.com Supply API
 *
 * The base URL for all API endpoints is https://api.rekki.com  Api key value contains of word Bearer together with api key that you can get from integrations@rekki.com 
 *
 * API version: 
 * Contact: integrations@rekki.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client
// V3StockItemState struct for V3StockItemState
type V3StockItemState struct {
	// only possible values are `in_stock` or `out_of_stock`
	Availability string `json:"availability"`
	ProductCode string `json:"product_code"`
}
