/*
 * Rekki.com Supply API
 *
 * The base URL for all API endpoints is https://api.rekki.com  Api key value contains of word Bearer together with api key that you can get from integrations@rekki.com 
 *
 * API version: 
 * Contact: integrations@rekki.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client
// MainOrderListOutput struct for MainOrderListOutput
type MainOrderListOutput struct {
	// list of not integrated orders
	Orders []IntegrationOrder `json:"orders,omitempty"`
}
